services:
  - type: web
    name: employee-service
    env: java
    branch: main
    repo: https://github.com/MITTAL1104/staff-backend
    rootDir: employee_service
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render-java/jdk
